/*
 * Package: fingerprint
 * File: chromaprint.go
 * Purpose: Invokes fpcalc binary to generate acoustic Chromaprint hashes from audio files.
 * Subsystem: Acoustic Fingerprinting Engine
 * Concurrency: Thread-safe; spawns isolated subprocesses with context timeout protection.
 */

package fingerprint

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// FingerprintResult encapsulates the acoustic duration and raw base64 Chromaprint hash.
type FingerprintResult struct {
	Duration    float64 `json:"duration"`
	Fingerprint string  `json:"fingerprint"`
}

// GenerateFingerprint executes the fpcalc binary with "-json" on the target audio file.
// If fpcalcPath is empty, it attempts to resolve "fpcalc" from the system PATH.
func GenerateFingerprint(ctx context.Context, fpcalcPath, filePath string) (*FingerprintResult, error) {
	if strings.TrimSpace(filePath) == "" {
		return nil, errors.New("audio file path must not be empty")
	}

	// Verify target file exists and is accessible
	info, err := os.Stat(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to access audio file %q: %w", filePath, err)
	}
	if info.IsDir() {
		return nil, fmt.Errorf("target path is a directory, not an audio file: %q", filePath)
	}

	bin, err := ResolveFpcalcBinary(fpcalcPath)
	if err != nil {
		return nil, err
	}

	cmd := exec.CommandContext(ctx, bin, "-json", filePath)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		errMsg := strings.TrimSpace(stderr.String())
		if errMsg != "" {
			return nil, fmt.Errorf("fpcalc failed (%w): %s", err, errMsg)
		}
		return nil, fmt.Errorf("fpcalc execution failed: %w", err)
	}

	return ParseFpcalcJSON(stdout.Bytes())
}

// ParseFpcalcJSON parses stdout JSON generated by "fpcalc -json".
func ParseFpcalcJSON(output []byte) (*FingerprintResult, error) {
	trimmed := bytes.TrimSpace(output)
	if len(trimmed) == 0 {
		return nil, errors.New("empty output received from fpcalc")
	}

	var res FingerprintResult
	if err := json.Unmarshal(trimmed, &res); err != nil {
		return nil, fmt.Errorf("failed to parse fpcalc JSON output: %w (raw output: %s)", err, string(trimmed))
	}

	if res.Duration <= 0 {
		return nil, fmt.Errorf("invalid audio duration in fpcalc result: %f", res.Duration)
	}
	if strings.TrimSpace(res.Fingerprint) == "" {
		return nil, errors.New("empty fingerprint hash in fpcalc result")
	}

	return &res, nil
}

// ResolveFpcalcBinary locates the fpcalc executable across PATH, backend/bin, and system paths.
func ResolveFpcalcBinary(fpcalcPath string) (string, error) {
	if strings.TrimSpace(fpcalcPath) != "" {
		if _, err := os.Stat(fpcalcPath); err == nil {
			return fpcalcPath, nil
		}
	}

	if resolved, err := exec.LookPath("fpcalc"); err == nil {
		return resolved, nil
	}

	candidates := []string{
		"bin/fpcalc.exe",
		"bin/fpcalc",
		"../bin/fpcalc.exe",
		"../bin/fpcalc",
		"backend/bin/fpcalc.exe",
		"backend/bin/fpcalc",
	}

	userProfile := os.Getenv("USERPROFILE")
	if userProfile != "" {
		candidates = append(candidates,
			filepath.Join(userProfile, "Downloads", "chromaprint-fpcalc-1.6.1-windows-x86_64", "chromaprint-fpcalc-1.6.1-windows-x86_64", "fpcalc.exe"),
			filepath.Join(userProfile, "Downloads", "chromaprint-fpcalc-1.6.1-windows-x86_64", "fpcalc.exe"),
		)
	}

	for _, cand := range candidates {
		if _, err := os.Stat(cand); err == nil {
			if abs, err := filepath.Abs(cand); err == nil {
				return abs, nil
			}
			return cand, nil
		}
	}

	return "", errors.New("fpcalc binary not specified and not found in PATH, backend/bin, or Downloads")
}

