/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/cubicreates/unbound-engine/cmd/android */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#if defined(__ANDROID__) || defined(ANDROID)
#include <jni.h>
#else
typedef struct _JNIEnv JNIEnv;
typedef void* jobject;
typedef void* jstring;
typedef int   jint;
#endif
#include <stdlib.h>

#if defined(__ANDROID__) || defined(ANDROID)
static const char* get_string_utf(JNIEnv *env, jstring str) {
    if (str == NULL || env == NULL) return NULL;
    return (*env)->GetStringUTFChars(env, str, NULL);
}

static void release_string_utf(JNIEnv *env, jstring str, const char* chars) {
    if (str != NULL && chars != NULL && env != NULL) {
        (*env)->ReleaseStringUTFChars(env, str, chars);
    }
}
#else
static const char* get_string_utf(JNIEnv *env, jstring str) { return NULL; }
static void release_string_utf(JNIEnv *env, jstring str, const char* chars) {}
#endif

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern jint Java_com_example_unboundtestfrontend_DaemonManager_startEngineNative(JNIEnv* env, jobject clazz, jstring jAppStoragePath, jint jPort);
extern jint Java_com_example_unboundtestfrontend_DaemonManager_stopEngineNative(JNIEnv* env, jobject clazz);
extern jint Java_com_cubicreates_unboundmusic_daemon_DaemonManager_startEngineNative(JNIEnv* env, jobject clazz, jstring jAppStoragePath, jint jPort);
extern jint Java_com_cubicreates_unboundmusic_daemon_DaemonManager_stopEngineNative(JNIEnv* env, jobject clazz);

#ifdef __cplusplus
}
#endif
